###########
# site.title

title:    'Tron.ai'
subtitle: 'CS 175: Project in AI'


#########################
# more settings

markdown: kramdown
kramdown:
  math_engine: null

exclude:
- README.md
- LICENSE.md
